### ISSUE TITLE
Minecraft RCON Connections return UnexpectedEof

### ISSUE THREAD

**Issue by AhiVT** [ikkerens/rercon#1]
Attempting to connect to a Minecraft 1.12 server using RCON produces a `IO(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })` error. This error is fatal.

**Comment by AhiVT** [comment]
Issue only appears when connecting to a server at localhost.

**Comment by blm768** [comment]
I've had similar issues with my own home-brewed RCON implementation for another project. This seems to be a bug in Minecraft's RCON implementation. Adding a short delay before sending each packet (including packets sent during the initial handshake) helped in my case.

**Comment by ikkerens** [comment]
As I did some testing, I've found that the issue no longer exists in later versions of Minecraft, which is good.
Though I understand version 1.12 is still widely in use in the modding community.

I'll see to it to add some way to add a timeout inbetween connection and the first auth message, allowing support on older Minecraft servers too. And maybe add an integration unit test to avoid regression.

Thank you @blm768 for the tip, in my tests this seems to work fine for this lib too.

**Comment by ikkerens** [comment]
I've implemented this by using a new Settings struct that needs to be passed to the connection constructor: https://github.com/ikkerens/rercon/blob/master/src/connection.rs#L25

I expect to release a new crate rather soon, but I hope to have fixed #2 first before I do, if that takes too long I'll prioritize the crate first.
