### ISSUE TITLE
Support for filtering out "keep-alive" packets

### ISSUE THREAD

**Issue by blm768** [ikkerens/rercon#2]
Recent versions of <i>ARK: Survival Evolved</i> periodically send a "keep-alive" packet with its ID set to 0 and its body set to "Keep Alive". This looks like a packet ID de-sync condition to clients that aren't prepared to filter out those packets.

Having some way of configuring response packets to drop (perhaps with a user-provided closure) would help in dealing with non-conformant server implementations like this one.

It's probably a good idea to have some kind of logic to make sure these filtered-out packets are removed from the TCP stream as they arrive, not just when waiting for a response. In theory, enough keep-alive packets piling up might fill the client's TCP buffers if it doesn't send commands for a while.

If you think this is a worthwhile feature, I'd be happy to put in some effort to implement it.

**Comment by ikkerens** [comment]
I've been looking into this myself for a bit as well, and does present a bit of a challenge for a protocol that only expects an answer when one is requested.

Like you said, if too much time passes the buffers might overflow, so the library would need some clientside thread that constantly reads out the stream and discards anything that is not requested (or alternatively filtered, but I feel just discarding them is the more... protocol-friendly way to do it).

**Comment by blm768** [comment]
Yeah; just discarding de-synced packets could be a reasonable approach. It might be as simple as spawning a background task that repeatedly calls `Packet::read` and processes packets as follows:

1. If the packet's ID matches the last command ID, append the body to a buffer somewhere.
2. If the packet's ID matches the last empty packet ID, clear the "last command/empty IDs" and put the buffer somewhere where the "main task" can get to it, i.e. by putting it in a bounded channel (which, in principle, should only have one item in it at a time).
3. Otherwise, discard the packet.

**Comment by blm768** [comment]
PR #5 should have taken care of this.
