### ISSUE TITLE
Use `std::net::ToSocketAddrs` (or equivalent) instead of  `Into<String>` for server addresses

### ISSUE THREAD

**Issue by blm768** [ikkerens/rercon#3]
Using `std::net::ToSocketAddrs` instead of `Into<String>` for the addresses passed into `Connection::open` would be handy. Users could directly provide a `SocketAddr` instead of a `String` if it's convenient for them, and it would enable hostname resolution.

The downside of using `ToSocketAddrs` is that it can block, so it would have to be wrapped in `tokio::task::spawn_blocking` or something.

**Comment by ikkerens** [comment]
Good catch on the socket addrs being blocking, I'll admit I hadn't even considered it on my initial async implementation. I'm working on this alongside some other features that I plan to push soon. Will close the issue when I do, though you're free to comment on the implementation.

**Comment by ikkerens** [comment]
As it happens, apparently tokio has its own lookup_host which is async.
I've implemented this here: https://github.com/ikkerens/rercon/blob/51b4def3fc5dc5b3ded51afef889216c20ed272e/src/connection.rs#L144-L170
